### ISSUE TITLE
Firefox 126 context menus are messed up

### ISSUE THREAD

**Issue by lanx73** [onemen/TabMixPlus#295]
Just manually updated Firefox to stable 126 version and it looks like TabMixPlus interferes with right-click menus both on tab bar and web page content: many items in context menus are disappeared.
After right-clicking here and there for a while, the items in context menus magically reappear, but this faulty behaviour recurs every time the browser is closed and reopened.

**Comment by onemen** [comment]
Go to our [download](https://onemen.github.io/tabmixplus-docs/download/) page
Download and install latest Tab Mix Plus version, if you are using Developer Edition, Beta or Nightly Firefox pleas download the latest development build

**Comment by lanx73** [comment]
> Go to our [download](https://onemen.github.io/tabmixplus-docs/download/) page Download and install latest Tab Mix Plus version, if you are using Developer Edition, Beta or Nightly Firefox pleas download the latest development build

I'm already working with latest TabMixPlus versions (1.19.1 in my main Firefox profile and 2024-05-12 Dev-build in secondary profile) and my bug-report concerns indeed their strange behaviour with final, stable Firefox 126.

Disabling TabMixPlus and restarting the browser makes the problem disappear, while reactivating the extension makes it appear again.

**Comment by lanx73** [comment]
In the attached image you can see the effects on the first right click and after repeatedly clicking here and there.

The context menu is progressively repopulated with the missing items.
![ff126](https://github.com/onemen/TabMixPlus/assets/39463313/4f6ebe6b-9317-4dab-a5ee-7845daf93fa1)

**Comment by onemen** [comment]
Firefox 126 is in Beta, use Tab Mix latest [development build](https://api.bitbucket.org/2.0/repositories/onemen/tabmixplus-for-firefox/downloads/tab_mix_plus-dev-build.xpi)

**Comment by lanx73** [comment]
Firefox 126 is no longer in beta stage: it has been released (but not yet as automatic update) and 127 beta cycle is already underway.
[https://ftp.mozilla.org/pub/firefox/releases/126.0/](url)

As I have said before, I'm already working with latest TabMixPlus versions (1.19.1 in my main Firefox profile and 2024-05-12 Dev-build in secondary profile) and the effects are exactly the same.

**Comment by onemen** [comment]
what language you are using? 
do you see the same issue on new clean profile?

**Comment by onemen** [comment]
I've just installed Italian Firefox 126 on my Windows 10 PC and everything works with Tab Mix Plus 1.19.1

**Comment by lanx73** [comment]
In fact, it looks like TabMixPlus remains in a sort of "limbo" for some time when Firefox starts up... so much so that even protected and locked tabs are not restored with the correct attributes.

I tried also on a new, clean profile, with same  results.

Now I have also inspected all of the utils/script and configuration files and found they were outdated.
After updating all of them on a fresh new profile and cleaning startup cache, now I get the error _"Failed to read configuration file. Please contact system administrator"_ even before installing TabMixPlus.

**Comment by onemen** [comment]
The latest configuration file is [here](https://github.com/onemen/TabMixPlus/files/14075743/fx-folder.zip)
https://onemen.github.io/tabmixplus-docs/other/installation/

**Comment by lanx73** [comment]
Well... just installed Firefox 126 US-english in another folder and created another fresh new profile.

Copied most up-to-date utils/script and configuration files in proper locations.

Cleaned startup cache and restarted.

Installed latest Dev TabMixPlus version (tried both with default settings and importing my custom settings) and opened three tabs: first one with a web page and set to "Freeze", second one with another web page and set to "Protected", third one set to "Blocked".

Closed Firefox and relaunched: no tabs retained their previous frozen/protected status.

Here you can see browser console error messages at Firefox startup.

```
12:31:38.493 1715682698493	addons.xpi	WARN	Checking C:\Program Files\Mozilla US-fox\distribution\extensions for addons
12:31:38.755 Applying chrome://tabmixplus/content/tabmix.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
12:31:38.758 Applying chrome://tabmixplus/content/overlay/tabContextMenu.xhtml to chrome://browser/content/browser.xhtml Overlays.jsm:96:15
12:31:38.758 Loading eval'd script into chrome://browser/content/browser.xhtml Overlays.jsm:567:15
12:31:38.758 Tabmix initializer: 
Object { key: "init", phase: {…} }
tabmix.js:1167:17
12:31:38.759 Tabmix initializer: 
Object { key: "beforeStartup", phase: {…} }
tabmix.js:1167:17
12:31:38.761 Tabmix initializer: 
Object { key: "onContentLoaded", phase: {…} }
tabmix.js:1167:17
12:31:38.787 Tabmix initializer: 
Object { key: "beforeBrowserInitOnLoad", phase: {…} }
tabmix.js:1167:17
12:31:38.792 Tabmix initializer: 
Object { key: "onWindowOpen", phase: {…} }
tabmix.js:1167:17
12:31:38.794 Tabmix:
change_utility was unable to change BrowserCloseTabOrWindow.
BrowserCloseTabOrWindow is undefined.

Try Tabmix latest development version from https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/,
Report about this to Tabmix developer at https://github.com/onemen/TabMixPlus/issues
changecode.js:163:17
12:31:38.794 Tabmix:
change_utility was unable to change nsBrowserAccess.prototype._openURIInNewTab.
can't find string
    win.BrowserOpenTab()

Try Tabmix latest development version from https://bitbucket.org/onemen/tabmixplus-for-firefox/downloads/,
Report about this to Tabmix developer at https://github.com/onemen/TabMixPlus/issues
changecode.js:163:17
12:31:38.798 Tabmix initializer: 
Object { key: "afterDelayedStartup", phase: {…} }
tabmix.js:1167:17
12:31:38.851 Tabmix TMP_ss_persistTabAttribute:
nsSessionStore could not add Attribute to persistTabAttribute: TypeError: TabmixSvc.ss.persistTabAttribute is not a function

2 sessionStore.js:118:14
12:31:39.701 BackgroundUpdate: maybeScheduleBackgroundUpdateTask: exiting after uncaught exception in maybeScheduleBackgroundUpdateTask! TypeError: this is undefined
    deleteTasksInRange resource://gre/modules/BackgroundUpdate.sys.mjs:78
    maybeScheduleBackgroundUpdateTask resource://gre/modules/BackgroundUpdate.sys.mjs:586
BackgroundUpdate.sys.mjs:687
12:31:58.415 <Provider> does not support changing `store` on the fly. It is most likely that you see this error because you updated to Redux 2.x and React Redux 2.x which no longer hot reload reducers automatically. See https://github.com/reactjs/react-redux/releases/tag/v2.0.0 for the migration instructions. react-redux.js:881:13

```

And here you can find my custom settings.
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/15307201/TMPpref.txt)

**Comment by onemen** [comment]
```
12:31:38.851 Tabmix TMP_ss_persistTabAttribute:
nsSessionStore could not add Attribute to persistTabAttribute:
 TypeError: TabmixSvc.ss.persistTabAttribute is not a function 

sessionStore.js:118:14
```
This issue was fixed by [commit 7d4b337](https://github.com/onemen/TabMixPlus/commit/7d4b3372a3c9a24d7fdc134632e1cdf976bbda77)

For Firefox 126 use Tab Mix latest [development build](https://api.bitbucket.org/2.0/repositories/onemen/tabmixplus-for-firefox/downloads/tab_mix_plus-dev-build.xpi)

**Comment by XeonG** [comment]
Maybe another issue but it seems I can't get the context menu to show for bookmarks that are in bookmark toolbar subfolders.. ie I can right click on a bookmark on a toolbar and get the context menu.. but if I do the same on a bookmark that is in a subfolder on the toolbar it doesn't show the menu.. likek it appears and gets removed instantly.. .

you used to be able to get the context menu like this.. I mean insanely dumb if mozilla have done this as you can't edit or rename a bookmark directly and instead have to open up its crap bookmark library manager window.... so I'm assuming a bug but don't know from where

**Comment by onemen** [comment]
Tab mix Plus [version 1.20.0](https://github.com/onemen/TabMixPlus/releases/download/v1.20.0/tab_mix_plus-1.20.0.xpi) is out

**Comment by AuRiMaS666** [comment]
I'm still having this very similar problem with the latest FF 126.0 / TMP 1.20.0 and updated firefox-scripts. This happens only in a freshly opened browser window when right clicking for the very first time within the page area. Tab bar and toolbar menus are not affected when clicked for the first time.

![2024-05-22_03-03-38](https://github.com/onemen/TabMixPlus/assets/59185222/a177c58b-325e-4e95-8d70-3bc104da6c1b)
![2024-05-22_03-03-07](https://github.com/onemen/TabMixPlus/assets/59185222/8be851c6-925a-4b0b-947e-72d3bb099775)
![2024-05-22_03-14-59](https://github.com/onemen/TabMixPlus/assets/59185222/a4f59764-9859-4d09-bb03-e012aba0ba6d)
[TMPpref.txt](https://github.com/onemen/TabMixPlus/files/15399498/TMPpref.txt)

**Comment by lanx73** [comment]
Looks like this is affecting ALL 126.0 non-US localized Firefox releases and TabMixPlus simply suffers the consequences of this problem by amplifying its effects and making it more visible.
Actually a big mess has been made at Mozilla, which without TabMixPlus is perceptible only by checking the browser console when it is launched.
[https://bugzilla.mozilla.org/show_bug.cgi?id=1897656](url)

This has been fixed as of Firefox 127.0b3 and the fix will also be included in 126.0.1 which will be released in the next few days.

**Comment by tagaga** [comment]
updated to 127b5, but the problem still remains unsolved.

**Comment by tagaga** [comment]
updated to 127b8,  the problem still remains unsolved.

**Comment by onemen** [comment]
@tagaga 
> updated to 127b8, the problem still remains unsolved.

I can not reproduce this issue.

please attach a file with your Tab Mix Plus preferences.

what language you are using?
can you test if the same issue exist on new profile?

**Comment by lanx73** [comment]
Well well... Firefox 126.0.1 has been released with all of the required fixes to prevent such problems to all people upgrading from 125.0.3 NON-US (localized) and earlier versions.

So, YES... this issue occurred because of some misunderstandings and problems inside the Mozilla Localization Teams during the building process of almost all localized Firefox 126 versions.

Unfortunately, people like me (and many other around the world) who already applied the update to the first 126.0 stable release won't get probably any chance to restore full functionality for some extensions (i.e. Bitwarden showing an endlessly spinning wheel instead of the vault).

I tried almost EVERYTHING to avoid starting from scratch with clean, new profiles but nothing worked for me and it has been literally a pain in the ass to carefully migrate data, extensions and settings from all of them, because I work with 9 different browser profiles for my specific business purposes, so... phew... many many hours spent in this process but, finally, now everything seems to work again like a charm!

Many people will not even notice what has happened under the hood because they make very mild and basic use of the browser and do not adopt all the customizations that, on the other hand, I and many others need for very specific purposes.

If you are interested, here is my report to Mozilla where you can also find links to all the other threads on the same topic.
[](https://bugzilla.mozilla.org/show_bug.cgi?id=1897656)

**Comment by AuRiMaS666** [comment]
So, what's the deal here in my case? With 126.0.1 I still get the same problem I posted above and my FF always was on en_US version since I started a fresh profile a few months back. Is re-doing the profile yet again is only potential solution here?

**Comment by lanx73** [comment]
I don't know exactly what's gone wrong or corrupted during the update from 125.0.3 to 126.0 but I haven't been able anymore to restore full functionality for Bitwarden extension, which kept showing that damn spinning wheel instead of my password vault and unexpectedly disconnecting from online account now and then.
An RSS-Feed extension was marked as corrupt and I have not been able to reactivate it since then, even uninstalling and reinstalling it.
TabMixPlus caused all of the above mentioned and shown issues with context menus in title bar, bookmarks bar and page content even with the most up-to-date development builds.

So, after days of trying to solve this inextricable tangle of problems I resigned myself and recreated the profiles from scratch with much patience and now everything works perfectly.

**Comment by AuRiMaS666** [comment]
That's interesting. Now that you've mentioned it, I realize that I had a few random logouts from Bitwarden's vault in recent weeks and it never did that before. Will try to observe the situation and decide how to proceed.

**Comment by FaRuukie** [comment]
en-US
FFX 126.0.1 (125.0.3 > 126.0 > 126.0.1)
TMP 1.20.0
latest fx-folder.zip and utils_extensions_and_scripts.zip

Page context menu works on the third time right-clicking.
Tab context menu works on the second time right-clicking.

You've asked for prefs.  Do you want logs (screenshot or copypaste)?
[TMPpref.txt](https://github.com/user-attachments/files/15522676/TMPpref.txt)

**Comment by onemen** [comment]
@117649 ,

Can you look at this issue?

When Tab Mix installed this error triggered from Tab Mix `Overlays.jsm`

```console
Uncaught TypeError: keyAttribute is null
    getKeyString resource://gre/modules/ShortcutUtils.sys.mjs:142
    prettifyShortcut resource://gre/modules/ShortcutUtils.sys.mjs:47
    accelText chrome://global/content/elements/menu.js:299
    _computeAccelTextFromKeyIfNeeded chrome://global/content/elements/menu.js:300
    render chrome://global/content/elements/menu.js:327
    connectedCallback chrome://global/content/elements/menu.js:343
    _insertElement chrome://tabmix-resource/content/bootstrap/Overlays.jsm:412
    _mergeElement chrome://tabmix-resource/content/bootstrap/Overlays.jsm:478
    _resolveForwardReference chrome://tabmix-resource/content/bootstrap/Overlays.jsm:363
    load chrome://tabmix-resource/content/bootstrap/Overlays.jsm:191
```

**Comment by onemen** [comment]
@FaRuukie

There is an issue with disabled Tab Mix shortcuts.

Go to Tab Mix preference Menu Shortcuts and reset the shortcuts for `Move the tab to a new window` and `Merges windows together`

I need to find what change in Firefox 126 that trigger this issue

**Comment by AuRiMaS666** [comment]
Can confirm that this has fixed the menu issue for me.

**Comment by onemen** [comment]
Download this [test build](https://github.com/user-attachments/files/15529632/test-build-1.21.0-20240603.0924.zip), rename it to .xpi and install it.

Report if it solved this issue

**Comment by lanx73** [comment]
YES... I tried this test build with an old Firefox profile still affected by such issues and they are finally vanished! Yo-hooo!!

**Comment by FaRuukie** [comment]
test-build-1.21.0-20240603.0924 seems to have fixed the context menus for me :)

I was slow returning to this thread and didn't try resetting shortcuts because, to be honest, installing the test build sounded like I wouldn't have to pay attention as much :p

My log is free of the red TMP entries.
Right-click works first time.

Things seem good.  I really dig this extension and I appreciate all the work done for it.  Thank you!
